import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import morgan from 'morgan';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import crypto from 'node:crypto';
import Razorpay from 'razorpay';
import {z} from 'zod';
import {v4 as uuid} from 'uuid';
import {getDb,updateDb} from './db.js';
dotenv.config();
const app=express();
const PORT=Number(process.env.PORT||5000); const JWT_SECRET=process.env.JWT_SECRET||'dev-secret-change-me';
const allowedOrigins=(process.env.CLIENT_URL||'http://localhost:5173,http://localhost:5174').split(',').map(x=>x.trim());
// Allow Vite's common local development ports.
const isLocalViteOrigin = origin => /^http:\/\/localhost:\d+$/.test(origin||'');
app.use(cors({origin:(origin,cb)=>{if(!origin||allowedOrigins.includes(origin)||isLocalViteOrigin(origin)) return cb(null,true); cb(new Error('CORS blocked'))},credentials:true}));
app.use(morgan('dev'));
app.use((req,res,next)=>{if(req.path==='/api/payments/webhook')return next();express.json()(req,res,next)});
const sign=u=>jwt.sign({id:u.id,email:u.email,role:u.role},JWT_SECRET,{expiresIn:'7d'});
function auth(req,res,next){try{const h=req.headers.authorization||''; if(!h.startsWith('Bearer ')) return res.status(401).json({message:'Authentication required'}); req.user=jwt.verify(h.slice(7),JWT_SECRET); next()}catch{return res.status(401).json({message:'Invalid or expired token'})}}
function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({message:'Admin access required'});next()}
const userSchema=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(6),phone:z.string().optional()});
app.get('/api/health',(req,res)=>res.json({ok:true,service:'Plately API',time:new Date().toISOString()}));
app.post('/api/auth/register',async(req,res)=>{try{const body=userSchema.parse(req.body);let db=getDb();if(db.users.some(u=>u.email.toLowerCase()===body.email.toLowerCase()))return res.status(409).json({message:'Email already registered'});const user={id:uuid(),name:body.name,email:body.email.toLowerCase(),phone:body.phone||'',passwordHash:await bcrypt.hash(body.password,12),role:'customer',createdAt:new Date().toISOString()};updateDb(d=>(d.users.push(user),d));const {passwordHash,...safe}=user;res.status(201).json({user:safe,token:sign(user)})}catch(e){res.status(400).json({message:e.issues?.[0]?.message||'Invalid registration'})}});
app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body||{};const u=getDb().users.find(x=>x.email===String(email||'').toLowerCase());if(!u||!(await bcrypt.compare(password||'',u.passwordHash)))return res.status(401).json({message:'Invalid email or password'});const {passwordHash,...safe}=u;res.json({user:safe,token:sign(u)})});
app.get('/api/auth/me',auth,(req,res)=>{const u=getDb().users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({message:'User not found'});const {passwordHash,...safe}=u;res.json({user:safe})});
app.get('/api/restaurants',(req,res)=>{const db=getDb();res.json(db.restaurants.map(r=>({...r,meals:db.meals.filter(m=>m.restaurantId===r.id)})))});
app.get('/api/meals',(req,res)=>res.json(getDb().meals));
app.get('/api/meals/:id',(req,res)=>{const m=getDb().meals.find(x=>x.id===req.params.id);m?res.json(m):res.status(404).json({message:'Meal not found'})});
const orderSchema=z.object({items:z.array(z.object({mealId:z.union([z.string(),z.number()]),quantity:z.number().int().min(1).max(20)})).min(1),customer:z.object({name:z.string().min(2),email:z.string().email(),phone:z.string().min(8),address:z.string().min(5)}),notes:z.string().max(300).optional()});
app.post('/api/orders',async(req,res)=>{try{const body=orderSchema.parse(req.body);const db=getDb();const items=body.items.map(i=>{const m=db.meals.find(x=>String(x.id)===String(i.mealId));if(!m)throw new Error(`Meal ${i.mealId} not found`);return {mealId:m.id,name:m.name,price:m.price,quantity:i.quantity,image:m.image}});const subtotal=items.reduce((s,i)=>s+i.price*i.quantity,0);const deliveryFee=subtotal>=499?0:39;const tax=Math.round(subtotal*0.05);const total=subtotal+deliveryFee+tax;const order={id:uuid(),userId:req.user?.id||null,items,customer:body.customer,notes:body.notes||'',subtotal,deliveryFee,tax,total,currency:process.env.CURRENCY||'INR',status:'created',paymentStatus:'pending',paymentProvider:'razorpay',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};updateDb(d=>(d.orders.push(order),d));res.status(201).json(order)}catch(e){res.status(400).json({message:e.issues?.[0]?.message||e.message||'Could not create order'})}});
app.get('/api/orders',auth,(req,res)=>res.json(getDb().orders.filter(o=>o.userId===req.user.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))));
app.get('/api/orders/:id',auth,(req,res)=>{const o=getDb().orders.find(x=>x.id===req.params.id && (x.userId===req.user.id||req.user.role==='admin'));o?res.json(o):res.status(404).json({message:'Order not found'})});
app.post('/api/orders/:id/cancel',auth,(req,res)=>{let found;updateDb(d=>{found=d.orders.find(o=>o.id===req.params.id&&(o.userId===req.user.id||req.user.role==='admin'));if(found&&['created','paid'].includes(found.status)){found.status='cancelled';found.updatedAt=new Date().toISOString()}return d});if(!found)return res.status(404).json({message:'Order not found or cannot be cancelled'});res.json(found)});
function razor(){if(!process.env.RAZORPAY_KEY_ID||!process.env.RAZORPAY_KEY_SECRET||process.env.RAZORPAY_KEY_ID.includes('your_'))return null;return new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET})}
app.post('/api/payments/create-order',async(req,res)=>{const {orderId}=req.body||{};const order=getDb().orders.find(o=>o.id===orderId);if(!order)return res.status(404).json({message:'Order not found'});if(order.paymentStatus==='paid')return res.status(409).json({message:'Order is already paid'});const rzp=razor();if(!rzp)return res.json({mode:'demo',keyId:null,amount:order.total*100,currency:order.currency,orderId:order.id,message:'Razorpay credentials are not configured. Use demo checkout.'});try{const rp=await rzp.orders.create({amount:order.total*100,currency:order.currency,receipt:order.id,notes:{platelyOrderId:order.id}});updateDb(d=>{const o=d.orders.find(x=>x.id===order.id);o.gatewayOrderId=rp.id;o.updatedAt=new Date().toISOString();return d});res.json({mode:'razorpay',keyId:process.env.RAZORPAY_KEY_ID,amount:rp.amount,currency:rp.currency,orderId:order.id,gatewayOrderId:rp.id})}catch(e){res.status(502).json({message:'Payment gateway error',detail:e.error?.description||e.message})}});
app.post('/api/payments/verify',(req,res)=>{const {orderId,razorpay_order_id,razorpay_payment_id,razorpay_signature,demo}=req.body||{};const order=getDb().orders.find(o=>o.id===orderId);if(!order)return res.status(404).json({message:'Order not found'});if(demo){updateDb(d=>{const o=d.orders.find(x=>x.id===orderId);o.paymentStatus='paid';o.status='confirmed';o.updatedAt=new Date().toISOString();d.payments.push({id:uuid(),orderId,provider:'demo',status:'paid',createdAt:new Date().toISOString()});return d});return res.json({verified:true,order:getDb().orders.find(x=>x.id===orderId)})}if(!process.env.RAZORPAY_KEY_SECRET)return res.status(400).json({message:'Razorpay is not configured'});const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${razorpay_order_id}|${razorpay_payment_id}`).digest('hex');if(expected!==razorpay_signature)return res.status(400).json({message:'Payment signature verification failed'});updateDb(d=>{const o=d.orders.find(x=>x.id===orderId);o.gatewayPaymentId=razorpay_payment_id;o.paymentStatus='paid';o.status='confirmed';o.updatedAt=new Date().toISOString();d.payments.push({id:uuid(),orderId,provider:'razorpay',paymentId:razorpay_payment_id,status:'paid',createdAt:new Date().toISOString()});return d});res.json({verified:true,order:getDb().orders.find(x=>x.id===orderId)})});
app.post('/api/payments/webhook',express.raw({type:'application/json'}),(req,res)=>{if(!process.env.RAZORPAY_WEBHOOK_SECRET)return res.json({received:true});const signature=req.headers['x-razorpay-signature'];const expected=crypto.createHmac('sha256',process.env.RAZORPAY_WEBHOOK_SECRET).update(req.body).digest('hex');if(signature!==expected)return res.status(400).send('Invalid signature');res.json({received:true})});
app.get('/api/admin/stats',auth,admin,(req,res)=>{const d=getDb();res.json({users:d.users.length,orders:d.orders.length,revenue:d.orders.filter(o=>o.paymentStatus==='paid').reduce((s,o)=>s+o.total,0),pending:d.orders.filter(o=>!['delivered','cancelled'].includes(o.status)).length})});
app.get('/api/admin/orders',auth,admin,(req,res)=>res.json(getDb().orders.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))));
app.patch('/api/admin/orders/:id',auth,admin,(req,res)=>{const allowed=['created','confirmed','preparing','out_for_delivery','delivered','cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({message:'Invalid status'});let o;updateDb(d=>{o=d.orders.find(x=>x.id===req.params.id);if(o){o.status=req.body.status;o.updatedAt=new Date().toISOString()}return d});o?res.json(o):res.status(404).json({message:'Order not found'})});
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:'Internal server error'})});
app.listen(PORT,()=>console.log(`🍽️ Plately API running on http://localhost:${PORT}`));
